DROP DATABASE IF EXISTS reviews;

CREATE DATABASE reviews;

\c reviews;

CREATE TABLE IF NOT EXISTS reviews (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer NOT NULL,
  rating numeric NOT NULL,
  review_date varchar NOT NULL,
  summary varchar(60) NOT NULL,
  body varchar(1000) NOT NULL CHECK (length(body) > 50),
  recommend boolean NOT NULL,
  reported boolean NOT NULL,
  reviewer_name varchar(60) NOT NULL,
  reviewer_email varchar(60) NOT NULL,
  response varchar,
  helpfulness smallint NOT NULL
);

CREATE TABLE IF NOT EXISTS reviews_photos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id integer REFERENCES reviews (id),
  photo_url varchar
);

CREATE TABLE IF NOT EXISTS characteristics (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer,
  characteristics_name varchar
);

CREATE TABLE IF NOT EXISTS characteristics_reviews (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  characteristic_id integer REFERENCES characteristics (id),
  review_id integer REFERENCES reviews (id),
  characteristic_value smallint
);

COPY reviews(id, product_id, rating, review_date, summary, body, recommend, reported, reviewer_name, reviewer_email, response, helpfulness)
FROM '/Users/harrisonzhao/Hack Reactor/SDC/Reviews Data/reviews.csv'
DELIMITER ','
CSV HEADER;

COPY reviews_photos(id, review_id, photo_url)
FROM '/Users/harrisonzhao/Hack Reactor/SDC/Reviews Data/reviews_photos.csv'
DELIMITER ','
CSV HEADER;

COPY characteristics(id, product_id, characteristics_name)
FROM '/Users/harrisonzhao/Hack Reactor/SDC/Reviews Data/characteristics.csv'
DELIMITER ','
CSV HEADER;

COPY characteristics_reviews(id, characteristic_id, review_id, characteristic_value)
FROM '/Users/harrisonzhao/Hack Reactor/SDC/Reviews Data/characteristic_reviews.csv'
DELIMITER ','
CSV HEADER;
